### ISSUE TITLE
Issue with 01-Ruby/06-Parsing/Optional-02-Your-First-Scraper

### ISSUE THREAD

**Issue by vescoyez** [lewagon/fullstack-challenges#114]
Your tests pass in my terminal but they can't be validated on kitt : "Your code could not be run under 60 seconds. Infinite loop? Slow API calls?"

[:octocat: exercise](https://github.com/lewagon/fullstack-challenges/tree/master/01-Ruby/06-Parsing/Optional-02-Your-First-Scraper)
@ssaunier

**Comment by twcctz500000** [comment]
https://plus.google.com/+LIUCHANGHSIEN
