### ISSUE TITLE
Executer les tests sur un autre bloc d'execution

### ISSUE THREAD

**Issue by aug-riedinger** [lewagon/fullstack-challenges#22]
https://github.com/lewagon/fullstack-challenges/blob/master/04-Front-End/04-Javascript-jQuery/01-DOM-Manipulation/application.js

Dans ce fichier, si l'élève fait une erreur de syntaxe, les tests disparaissent, ce qui l'intrigue bien avant de comprendre la raison.

Il serait plus pratique d'exécuter ces tests dans un autre bloc, pour ne pas qu'une erreur de syntaxe les interrompe ...
Je suis conscient que ça n'est pas trivial mais ça doit être possible. :smile:

**Comment by ssaunier** [comment]
won't fix, la solution de dire aux students de prendre le réflexe de regarder la console pour des erreurs de syntaxe est suffisante (et un bon reflexe à acquérir) IMHO
