### ISSUE TITLE
Issue with 01-Ruby/06-Parsing/01-CSV-Parsing

### ISSUE THREAD

**Issue by maximedelpit** [lewagon/fullstack-challenges#35]
Bonjour Sébastien,

Message couplé avec celui de Sonia qui arrive ;-)

[:octocat: exercise](https://github.com/lewagon/fullstack-challenges/tree/master/01-Ruby/06-Parsing/01-CSV-Parsing)

**Comment by ssaunier** [comment]
Duplicate of #36
