### ISSUE TITLE
Issue with 01-Ruby/06-Parsing/01-CSV-Parsing

### ISSUE THREAD

**Issue by soniaprevost** [lewagon/fullstack-challenges#36]
Bonjour Sébastien,

Ce serait trop sympa si tu pouvais bump Kitt de ruby 2.1.2 à ruby 2.2.0 que nous utilisons.
Car vois-tu, nous sommes trop swag au Wagon alors nous avons utilisé la nouvelle signature de max qui peut prendre un paramètre : 

- ruby 2.1.2 http://ruby-doc.org/core-2.1.2/Enumerable.html#method-i-max
- ruby 2.2.0 http://ruby-doc.org/core-2.2.0/Enumerable.html#method-i-max

Merci !
Bisous

[:octocat: exercise](https://github.com/lewagon/fullstack-challenges/tree/master/01-Ruby/06-Parsing/01-CSV-Parsing)

**Comment by ssaunier** [comment]
Ma chère @soniaprevost , j'aimerais tellement satisfaire ce swag légendaire des élèves du wagon, mais pour la petite histoire Kitt est sur AWS Elastic Beanstalk qui ne supporte que la version 2.1 de Ruby pour l'instant :( :( :( du coup vous allez devoir vous contenter de la syntaxe 2.1 pour l'instant... cc @cveneziani

**Comment by ssaunier** [comment]
Kitt tourne maintenant en 2.2.2

**Comment by cveneziani** [comment]
Cool!
