### ISSUE TITLE
Issue with 03-AR-Database/01-DB-Design-and-SQL/02-Interacting-with-db

### ISSUE THREAD

**Issue by maximedelpit** [lewagon/fullstack-challenges#42]
Salut,

Problème au niveau du rake:
1) The schema in jukebox.xml the `albums` table should have a `artist_id` column, foreign key to `artists` table
     Failure/Error: row.elements["relation"].attributes["table"] == foreign_table_name
     NoMethodError:
       undefined method `elements' for nil:NilClass
     # ./spec/jukebox_spec.rb:48:in `foreign_key_exists?'
     # ./spec/jukebox_spec.rb:22:in `block (3 levels) in <top (required)>'

Alors que la connexion semble bien faite entre albums / artist_id /artists

[:octocat: exercise](https://github.com/lewagon/fullstack-challenges/tree/master/03-AR-Database/01-DB-Design-and-SQL/02-Interacting-with-db)

**Comment by ssaunier** [comment]
Le XML que tu as dans ton code donne ça:

![schema](https://cloud.githubusercontent.com/assets/414418/5873432/a11829de-a2f6-11e4-9cc0-28b289cc2267.png)

C'est bizarre, il y a deux tables `albums`, et il manque des liens.

**Comment by maximedelpit** [comment]
Yes étrange, bah je vais re-uploader ca.

Merci et A+


2015-01-23 11:55 GMT+01:00 Sébastien Saunier <notifications@github.com>:
